language: python
python:
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
# command to run tests
script:
  - coverage run -m pytest
  - coverage report
after_success:
- coveralls