language: python
python:
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
env:
  global:
    - ENV='Testing'
  services:
    - postgresql
before_script:
  - "psql -c 'create database Ireporter_test_db;' -u postgres"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
# command to run tests
script:
  - coverage run -m pytest
  - coverage report
after_success:
- coveralls